# Generated by Django 2.2.7 on 2019-12-01 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='career',
            field=models.CharField(default='Programmer', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='name',
            field=models.CharField(default='Name', max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
