# Generated by Django 2.2.7 on 2019-12-01 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191201_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageprojects',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
    ]
