# Generated by Django 2.2.7 on 2019-12-01 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191201_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageprojects',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
