# Generated by Django 2.2.7 on 2019-12-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0007_auto_20191201_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePageCarouselImages',
            new_name='HomePageProjects',
        ),
    ]
