# Generated by Django 2.2.7 on 2019-12-01 13:11

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191201_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageprojects',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepageprojects',
            name='name',
            field=models.CharField(default='Name', max_length=30),
        ),
    ]
