# Generated by Django 2.2.7 on 2019-12-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20191201_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cv',
            field=models.URLField(blank=True),
        ),
    ]
