# Generated by Django 2.2.7 on 2019-12-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191201_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='address',
            field=models.CharField(default='Egypt, Giza', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='email',
            field=models.EmailField(default='zfcon@zfcon.com', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='phone',
            field=models.CharField(default='+201000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
